/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author RoseLandjlord
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemIniciar = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemProductos = new javax.swing.JMenuItem();
        jmiCliente = new javax.swing.JMenuItem();
        jmiProveedores = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiCompras = new javax.swing.JMenuItem();
        jmiVentas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmiReporteClientes = new javax.swing.JMenuItem();
        jmiReporteProductos = new javax.swing.JMenuItem();
        jmiReporteProveedores = new javax.swing.JMenuItem();
        jmiReporteCompras = new javax.swing.JMenuItem();
        jmiReporteVenta = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 204));

        jMenu1.setText("Archivos");

        jMenuItemIniciar.setText("Iniciar Sesion");
        jMenu1.add(jMenuItemIniciar);

        jMenuItemUsuario.setText("Usuario");
        jMenu1.add(jMenuItemUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Catalogos");

        jMenuItemProductos.setText("Productos");
        jMenu2.add(jMenuItemProductos);

        jmiCliente.setText("Clientes");
        jMenu2.add(jmiCliente);

        jmiProveedores.setText("Proveedores");
        jMenu2.add(jmiProveedores);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Operaciones");

        jmiCompras.setText("Compras");
        jMenu6.add(jmiCompras);

        jmiVentas.setText("Ventas");
        jMenu6.add(jmiVentas);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Reportes");

        jmiReporteClientes.setText("Clientes");
        jMenu7.add(jmiReporteClientes);

        jmiReporteProductos.setText("Productos");
        jMenu7.add(jmiReporteProductos);

        jmiReporteProveedores.setText("Proveedores");
        jMenu7.add(jmiReporteProveedores);

        jmiReporteCompras.setText("Compras");
        jMenu7.add(jmiReporteCompras);

        jmiReporteVenta.setText("Ventas");
        jMenu7.add(jmiReporteVenta);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    public javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItemIniciar;
    public javax.swing.JMenuItem jMenuItemProductos;
    public javax.swing.JMenuItem jMenuItemUsuario;
    public javax.swing.JMenuItem jmiCliente;
    public javax.swing.JMenuItem jmiCompras;
    public javax.swing.JMenuItem jmiProveedores;
    public javax.swing.JMenuItem jmiReporteClientes;
    public javax.swing.JMenuItem jmiReporteCompras;
    public javax.swing.JMenuItem jmiReporteProductos;
    public javax.swing.JMenuItem jmiReporteProveedores;
    public javax.swing.JMenuItem jmiReporteVenta;
    public javax.swing.JMenuItem jmiVentas;
    // End of variables declaration//GEN-END:variables
}
